# Generated by Django 5.1.6 on 2026-06-14 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=80)),
                ('assay_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('QC_REVIEW', 'QC review'), ('RELEASED', 'Released'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assay_runs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assay_runs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QcMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_metrics', to='assays.assayrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assayrun',
            constraint=models.UniqueConstraint(fields=('organization', 'external_id'), name='unique_assay_run_external_id'),
        ),
    ]
